"""Synthetic speech attacks, generated by signal processing.

A spoofing countermeasure cannot be trained without spoofed material, and the
gate in :mod:`viflap.analysis.spoof.gate` is inert until one exists. These are
the attacks available without a neural text-to-speech model: analysis and
resynthesis of real recordings, each discarding a different property of natural
speech.

What these are, and what they are not
-------------------------------------
They are **vocoder-class attacks**. Every one of them takes a genuine recording,
decomposes it, throws away something a human vocal tract produces, and puts the
signal back together. That is exactly the artefact family that classical
parametric synthesis and voice conversion leave behind, and it is what a
countermeasure trained on them will learn to find.

They are **not neural synthesis**. A modern diffusion or flow vocoder leaves far
subtler traces, and a detector trained only on these will not generalise to one
— which is not a limitation peculiar to this module but the known central
weakness of every spoofing countermeasure, and the reason
:class:`~viflap.analysis.spoof.gate.GatePolicy` treats out-of-domain frames as
grounds for ``INDETERMINATE`` rather than trusting the score. A system honest
about that failure can be deployed; one that assumes its detector generalises
cannot.

Four families, because one is worth nothing
-------------------------------------------
:class:`~viflap.analysis.spoof.countermeasure.TrainingExample` requires an
``attack_id`` so that evaluation can hold attacks out. A countermeasure scored
on the attack family it trained on reports the number that overstates its
performance, and reports it confidently. Four families that fail differently
make a cross-attack evaluation possible:

``lpc_noise``
    All-pole resynthesis driven by white noise. Destroys the excitation
    entirely: no periodicity, no glottal pulse structure.
``lpc_pulse``
    All-pole resynthesis driven by a pulse train. Excitation is periodic but
    mechanically so, with none of the cycle-to-cycle variation of a real larynx.
``phase_randomised``
    The magnitude spectrum is kept and the phase discarded. Mimics
    magnitude-only synthesis, where the waveform is reconstructed from a
    spectrogram that never carried phase.
``oversmoothed``
    The excitation is left **genuine** and only the vocal tract filter is
    smoothed across time. Isolates the over-smoothed formant trajectory that is
    the signature artefact of statistical parametric synthesis.

The first three attack the source and the fourth attacks the filter, so a
detector cannot pass a cross-attack test by learning one axis.

Energy is preserved per frame, deliberately
-------------------------------------------
Every attack matches the energy of the frame it replaces. An attack detectable
by loudness alone would make the countermeasure look far better than it is, and
the resulting equal error rate would be measuring a level difference introduced
by this module rather than anything about synthetic speech.
"""

from __future__ import annotations

from collections.abc import Callable, Mapping
from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray
from scipy.signal import lfilter

from viflap.analysis.dsp.lpc import (
    autocorrelation,
    levinson_durbin,
    lpc_analysis,
    lpc_residual,
    recommended_order,
)
from viflap.domain.errors import (
    ConvergenceError,
    InsufficientDataError,
    InvalidEvidenceError,
)

__all__ = [
    "ATTACKS",
    "Attack",
    "apply_attack",
    "lpc_noise",
    "lpc_pulse",
    "oversmoothed",
    "phase_randomised",
]

#: Analysis frame, in samples at 16 kHz, and a half-frame hop. A Hann window at
#: fifty percent overlap sums to a constant, so overlap-add reconstructs without
#: needing a synthesis window or a normalisation pass — and a reconstruction
#: that is not exact would be an artefact this module introduced rather than one
#: the attack represents.
_FRAME_MS = 25.0
_HOP_DIVISOR = 2


def _geometry(sample_rate: int) -> tuple[int, int]:
    frame_length = int(round(_FRAME_MS * sample_rate / 1000.0))
    frame_length += frame_length % 2  # even, so the half-overlap is exact
    return frame_length, frame_length // _HOP_DIVISOR


def _frame(
    signal: NDArray[np.float64], sample_rate: int
) -> tuple[NDArray[np.float64], int, int]:
    """Windowed frames without pre-emphasis, for analysis-resynthesis.

    The front-end's framing is not reused here: it pre-emphasises and dithers,
    which are right for feature extraction and wrong for a signal that has to be
    put back together and sound like a recording.
    """
    frame_length, hop = _geometry(sample_rate)
    if signal.size < frame_length:
        raise InsufficientDataError(
            "signal is shorter than one analysis frame",
            n_samples=int(signal.size),
            frame_length=frame_length,
        )
    n_frames = 1 + (signal.size - frame_length) // hop
    window = np.hanning(frame_length)
    frames = np.stack(
        [
            signal[index * hop : index * hop + frame_length] * window
            for index in range(n_frames)
        ]
    )
    return frames, frame_length, hop


def _overlap_add(frames: NDArray[np.float64], hop: int, length: int) -> NDArray[np.float64]:
    """Reassemble frames, then restore the original peak."""
    frame_length = frames.shape[1]
    output: NDArray[np.float64] = np.zeros(length, dtype=np.float64)
    for index in range(frames.shape[0]):
        start = index * hop
        output[start : start + frame_length] += frames[index]
    return output


def _match_energy(
    synthetic: NDArray[np.float64], original: NDArray[np.float64]
) -> NDArray[np.float64]:
    """Scale a synthesised frame to the energy of the frame it replaces."""
    target = float(np.sqrt(np.mean(original**2)))
    produced = float(np.sqrt(np.mean(synthetic**2)))
    if produced <= 1e-12:
        return np.zeros_like(synthetic)
    return synthetic * (target / produced)


#: Reflection coefficients are bounded by one for a stable filter. Held just
#: inside so that a pole cannot land on the unit circle through rounding.
_MAX_REFLECTION = 0.999


def _lpc_from_reflection(reflection: NDArray[np.float64]) -> NDArray[np.float64]:
    """Step-up recursion: reflection coefficients to prediction-error filter.

    The inverse of what Levinson-Durbin produces on the way down, and the same
    recursion in the same convention — ``A(z) = 1 + sum a_k z^-k``.
    """
    order = int(reflection.size)
    a: NDArray[np.float64] = np.zeros(order + 1, dtype=np.float64)
    a[0] = 1.0
    for step in range(1, order + 1):
        k = float(reflection[step - 1])
        previous = a[1:step].copy()
        a[1:step] = previous + k * previous[::-1]
        a[step] = k
    return a


def _smooth_filters(
    frames: NDArray[np.float64], order: int, smooth_frames: int
) -> NDArray[np.float64]:
    """Smooth the vocal tract filter across time, in a domain where that is safe.

    Averaging all-pole *polynomial* coefficients does not preserve stability.
    Two stable filters can average to one with poles outside the unit circle,
    and the synthesis filter then diverges — the samples overflow and the
    recording becomes NaN. The failure is data-dependent, so it survives a spot
    check on one file and appears later on another, which is how it reached a
    training run here before a test caught it.

    Reflection coefficients have magnitude below one exactly when the filter is
    stable, and the mean of values inside ``(-1, 1)`` is inside ``(-1, 1)``. So
    the smoothing is done there and the polynomial is rebuilt afterwards, which
    makes stability a property of the representation rather than something to
    check for and repair.
    """
    reflections = np.zeros((frames.shape[0], order), dtype=np.float64)
    for index in range(frames.shape[0]):
        try:
            r = autocorrelation(frames[index], order)
            _, _, reflection = levinson_durbin(r, order)
        except (ConvergenceError, InvalidEvidenceError):
            # A silent or degenerate frame. Left at zero, which is the
            # reflection sequence of a flat filter: no resonance, no instability.
            continue
        reflections[index, : reflection.size] = reflection[:order]

    kernel = np.ones(smooth_frames) / smooth_frames
    smoothed = np.empty_like(reflections)
    for column in range(order):
        smoothed[:, column] = np.convolve(reflections[:, column], kernel, mode="same")
    np.clip(smoothed, -_MAX_REFLECTION, _MAX_REFLECTION, out=smoothed)

    return np.stack([_lpc_from_reflection(row) for row in smoothed])


def _resynthesise(
    signal: NDArray[np.float64],
    sample_rate: int,
    excitation_for: Callable[[NDArray[np.float64], int], NDArray[np.float64]],
    smooth_frames: int = 0,
) -> NDArray[np.float64]:
    """Analyse, replace the excitation, and put the signal back together."""
    frames, _frame_length, hop = _frame(signal, sample_rate)
    order = recommended_order(sample_rate)
    coefficients, _ = lpc_analysis(frames, order)

    if smooth_frames > 1:
        coefficients = _smooth_filters(frames, order, smooth_frames)

    synthetic = np.empty_like(frames)
    for index in range(frames.shape[0]):
        excitation = excitation_for(frames[index], index)
        produced = lfilter([1.0], coefficients[index], excitation)
        synthetic[index] = _match_energy(produced, frames[index])

    return _overlap_add(synthetic, hop, signal.size)


def lpc_noise(
    signal: NDArray[np.float64], sample_rate: int, rng: np.random.Generator
) -> NDArray[np.float64]:
    """All-pole resynthesis driven by white noise."""

    def excitation(frame: NDArray[np.float64], _index: int) -> NDArray[np.float64]:
        return rng.standard_normal(frame.size)

    return _resynthesise(signal, sample_rate, excitation)


def lpc_pulse(
    signal: NDArray[np.float64],
    sample_rate: int,
    _rng: np.random.Generator | None = None,
    f0_hz: float = 120.0,
) -> NDArray[np.float64]:
    """All-pole resynthesis driven by a pulse train.

    One fixed fundamental throughout, which is itself part of the attack: a
    monotone pitch contour is what a parametric synthesiser produces when its
    prosody model is weak, and it is audibly and measurably not a person.

    Deterministic — there is nothing to draw. The generator is accepted anyway
    so that every attack has one signature and the registry can call them
    interchangeably.
    """
    period = max(2, int(round(sample_rate / f0_hz)))

    def excitation(frame: NDArray[np.float64], index: int) -> NDArray[np.float64]:
        pulses = np.zeros(frame.size)
        # Continue the pulse phase across frames rather than restarting it each
        # time, which would place a pulse at every frame boundary and put a
        # periodic artefact at the hop rate into the signal.
        offset = (index * (frame.size // _HOP_DIVISOR)) % period
        pulses[np.arange(offset, frame.size, period)] = 1.0
        return pulses

    return _resynthesise(signal, sample_rate, excitation)


def oversmoothed(
    signal: NDArray[np.float64],
    sample_rate: int,
    _rng: np.random.Generator | None = None,
    smooth_frames: int = 9,
) -> NDArray[np.float64]:
    """Genuine excitation through a filter smoothed across time.

    The excitation is the recording's own residual, so whatever this attack is
    detectable by, it is not the source. That isolates the filter artefact.

    Deterministic, like :func:`lpc_pulse`: nothing here is drawn.
    """
    frames, _, _ = _frame(signal, sample_rate)
    order = recommended_order(sample_rate)
    coefficients, _ = lpc_analysis(frames, order)
    residual = lpc_residual(frames, coefficients)

    def excitation(_frame: NDArray[np.float64], index: int) -> NDArray[np.float64]:
        row: NDArray[np.float64] = residual[index]
        return row

    return _resynthesise(signal, sample_rate, excitation, smooth_frames=smooth_frames)


def phase_randomised(
    signal: NDArray[np.float64], sample_rate: int, rng: np.random.Generator
) -> NDArray[np.float64]:
    """The magnitude spectrum preserved, the phase discarded.

    Frame by frame the magnitudes are the original's, so a front-end reading
    frame spectra sees almost the same thing — the mean frame spectrum
    correlates above 0.9 with the original, and above 0.99 in the log domain.
    What is gone is the phase coherence that makes a waveform sound like a
    voice, which is precisely the property a countermeasure has to learn to use.

    The whole-signal spectrum is *not* preserved, and that is expected rather
    than a defect: overlap-adding frames with randomised phase makes them sum
    incoherently. Only the per-frame view is the one features are computed on.
    """
    frames, frame_length, hop = _frame(signal, sample_rate)

    synthetic = np.empty_like(frames)
    for index in range(frames.shape[0]):
        spectrum = np.fft.rfft(frames[index])
        phase = rng.uniform(-np.pi, np.pi, spectrum.size)
        # DC and Nyquist are real in a real-signal spectrum; giving them an
        # imaginary part would make the inverse transform complex.
        phase[0] = 0.0
        if frame_length % 2 == 0:
            phase[-1] = 0.0
        randomised = np.abs(spectrum) * np.exp(1j * phase)
        produced = np.fft.irfft(randomised, n=frame_length)
        synthetic[index] = _match_energy(produced * np.hanning(frame_length), frames[index])

    return _overlap_add(synthetic, hop, signal.size)


@dataclass(frozen=True, slots=True)
class Attack:
    """One attack family, with the identity evaluation needs to hold it out."""

    attack_id: str
    description: str
    generate: Callable[[NDArray[np.float64], int, np.random.Generator], NDArray[np.float64]]


ATTACKS: Mapping[str, Attack] = {
    attack.attack_id: attack
    for attack in (
        Attack("lpc_noise", "all-pole resynthesis, white noise excitation", lpc_noise),
        Attack("lpc_pulse", "all-pole resynthesis, pulse train excitation", lpc_pulse),
        Attack(
            "phase_randomised",
            "magnitude spectrum preserved, phase discarded",
            phase_randomised,
        ),
        Attack(
            "oversmoothed",
            "genuine excitation, formant trajectory smoothed across time",
            oversmoothed,
        ),
    )
}


def apply_attack(
    attack_id: str,
    signal: NDArray[np.float64],
    sample_rate: int,
    rng: np.random.Generator,
) -> NDArray[np.float64]:
    """Generate one spoofed version of a recording."""
    if attack_id not in ATTACKS:
        raise InsufficientDataError(
            f"unknown attack {attack_id!r}", available=sorted(ATTACKS)
        )
    return ATTACKS[attack_id].generate(signal, sample_rate, rng)
