"""End-to-end with the real comparators, on incidents that share a cause.

``test_pipeline.py`` drives the same use cases through a scalar test double. That
is the right test for the orchestration and the governance, and it is the wrong
one for everything below them: with a scalar signature per incident, no profile
is built, no background is consulted, no conjugate model is evaluated, and the
fusion model never sees four streams generated by one operator running one
operation. Every defect in that seam is invisible to it.

These tests put the analysis layer on the path. What they assert is **structure**,
not performance — the same standard ``test_synthetic_incidents.py`` sets, and for
a stronger reason here: the corpus is simulated, so a performance figure taken off
it would be a property of the generative parameters. §11 of the results document
was withdrawn for exactly that, and nothing in this file may be quoted as a
measurement.

The one near-numeric assertion, on the ordering of median fused values, is a
wiring check. It fails if payloads are handed to the wrong stream or a calibrator
comes out sign-inverted, which are the defects this seam actually produces. It is
not a claim that the system discriminates at any rate.
"""

from __future__ import annotations

import numpy as np
import pytest

from scripts.synthesise_incidents import generate
from scripts.synthetic_pipeline import (
    STREAMS,
    WARNING,
    AssembledSystem,
    _pairs,
    assemble,
    enrol,
    payloads_for,
)
from viflap.analysis.patterns.streams import CallRecord, TemporalProfile
from viflap.application.comparison import ComparisonRequest
from viflap.application.ports import EvidenceBundle
from viflap.application.search import SearchRequest
from viflap.domain.evidence import (
    AbsenceReason,
    EvidenceStream,
    StreamAbsent,
    StreamEvidence,
)
from viflap.domain.governance import (
    AnalystRole,
    CaseReference,
    OutputLanguagePolicy,
    Principal,
)
from viflap.domain.hypotheses import PriorOdds
from viflap.domain.linkage import IncidentPair

#: Sized so the development partition clears ``MIN_TRIALS_PER_CLASS`` with room
#: to spare — 113 same-operator pairs against the 30 a calibrator needs — while
#: fitting in under two seconds.
CORPUS = {"n_operators": 18, "n_operations": 8, "incidents_per_operation": 10}


@pytest.fixture(scope="module")
def corpus():
    _, _, incidents = generate(**CORPUS)
    return incidents


@pytest.fixture(scope="module")
def case_ref() -> CaseReference:
    return CaseReference.parse("ZP-2026-00042")


@pytest.fixture(scope="module")
def officer() -> Principal:
    return Principal("enrol-sim", frozenset({AnalystRole.ENROLMENT_OFFICER}))


@pytest.fixture(scope="module")
def analyst() -> Principal:
    return Principal("inv-sim", frozenset({AnalystRole.INVESTIGATOR}))


@pytest.fixture(scope="module")
def system(tmp_path_factory, corpus) -> AssembledSystem:
    """Fitted once: backgrounds, four calibrators and a fusion model.

    Module-scoped because fitting reads every background incident and scores
    every development pair, and repeating that per test would dominate the suite
    for no additional coverage.
    """
    path = tmp_path_factory.mktemp("synthetic-pipeline") / "audit.jsonl"
    return assemble(corpus, path)


@pytest.fixture(scope="module")
def enrolled(system, case_ref, officer):
    return enrol(system, system.partitions.evaluation, case_ref, officer)


def _compare(system, analyst, case_ref, first, second):
    store = system.unit_of_work.store.evidence
    return system.compare.execute(
        ComparisonRequest(
            pair=IncidentPair(first, second, case_ref),
            prior=PriorOdds.uniform_over_database(64),
            requested_by=analyst,
        ),
        store[first.value],
        store[second.value],
    )


class TestTheSplitHoldsUp:
    def test_no_operator_appears_in_two_partitions(self, system) -> None:
        """A calibrator fitted on the operators it later scores describes them.

        Nothing else in the pipeline checks this: every partition is internally
        consistent, and the leak would be between them, which is the shape of
        defect §9 found when two models were scored on each other's speakers.
        """
        groups = [set(names) for names in system.partitions.operators.values()]
        background, development, evaluation = groups
        assert not background & development
        assert not background & evaluation
        assert not development & evaluation

    def test_every_partition_has_incidents(self, system) -> None:
        summary = system.partitions.summary()
        for key in (
            "background_incidents",
            "development_incidents",
            "evaluation_incidents",
        ):
            assert summary[key] > 0, key

    def test_operations_are_allowed_to_straddle_the_split(self, system) -> None:
        """Splitting by operation would put script evidence beyond reach.

        The behavioural stream's script component exists to link incidents across
        operators of one operation. If no operation spanned two partitions, no
        cross-partition comparison could ever exercise it.
        """
        of = lambda incidents: {incident.operation_id for incident in incidents}  # noqa: E731
        assert of(system.partitions.development) & of(system.partitions.evaluation)


class TestEveryStreamReachesTheEngine:
    def test_all_four_streams_produce_calibrated_evidence(
        self, system, enrolled, analyst, case_ref
    ) -> None:
        """The claim the scalar double cannot support.

        A stream silently returning absence — because its background was empty,
        its payload was the wrong type, or its calibrator was never fitted — is
        indistinguishable from a working stream in any test that does not look.
        """
        result = _compare(system, analyst, case_ref, enrolled[0], enrolled[1])
        for stream in STREAMS:
            outcome = result.outcomes[stream]
            assert isinstance(outcome, StreamEvidence), (
                f"{stream.value} produced {outcome!r} rather than evidence"
            )
            assert np.isfinite(outcome.log_lr.value)

    def test_each_stream_names_the_models_that_produced_it(
        self, system, enrolled, analyst, case_ref
    ) -> None:
        """A likelihood ratio whose scorer and calibrator are unrecorded cannot
        be reproduced when it is challenged."""
        result = _compare(system, analyst, case_ref, enrolled[0], enrolled[1])
        for stream in STREAMS:
            model_id = result.outcomes[stream].model_id
            assert "+" in model_id, f"{stream.value} model id lacks a calibrator: {model_id}"

    def test_the_behavioural_decomposition_survives_to_the_result(
        self, system, enrolled, analyst, case_ref
    ) -> None:
        """"Same operation, probably not the same person" is only visible here."""
        result = _compare(system, analyst, case_ref, enrolled[0], enrolled[1])
        diagnostics = result.outcomes[EvidenceStream.BEHAVIOURAL].diagnostics
        assert "idiolect_component" in diagnostics
        assert "script_component" in diagnostics
        assert "suggests_delegation" in diagnostics

    def test_the_idiolect_term_is_actually_scored(
        self, system, enrolled, analyst, case_ref
    ) -> None:
        """The corpus must be long enough to reach the half that has a citation.

        The behavioural comparator withholds the idiolect term below
        ``MIN_WORDS_IDIOLECT`` and still returns a score from the script term
        alone, so every other assertion in this file passes either way. Without
        this one, shortening the transcripts would quietly reduce the stream to
        its unbenchmarked half.
        """
        result = _compare(system, analyst, case_ref, enrolled[0], enrolled[1])
        diagnostics = result.outcomes[EvidenceStream.BEHAVIOURAL].diagnostics
        assert diagnostics["idiolect_was_withheld"] == 0.0
        assert diagnostics["idiolect_component"] != 0.0

    def test_device_evidence_reports_the_rarity_it_rested_on(
        self, system, enrolled, analyst, case_ref
    ) -> None:
        """A shared IMEI is the strongest observation this system handles, and
        how rare that handset is in the background is what makes it so."""
        result = _compare(system, analyst, case_ref, enrolled[0], enrolled[1])
        diagnostics = result.outcomes[EvidenceStream.DEVICE].diagnostics
        assert "n_shared_imei" in diagnostics
        assert "rarest_shared_imei_frequency" in diagnostics


class TestFusionMeetsRealDependence:
    def test_the_fitted_model_finds_the_shared_cause(self, system) -> None:
        """The corpus generates one operator running one operation as the common
        cause of all four streams. If fusion estimated no dependence, either the
        generator stopped producing it or the streams stopped seeing it, and both
        are silent failures.
        """
        summary = system.back_end.fusion.common_factor()
        assert summary.shared_variance_fraction > 0.05
        assert max(abs(value) for value in summary.loadings.values()) > 0.3

    # A stronger assertion was tried here and withdrawn. Because the handset
    # pool, the cell sites, the agents and the counterparty wallets are all the
    # *operation's* property, the transactional and device streams should carry
    # the common factor more strongly than the operator-level behavioural one.
    # At the default seed they do, by a wide margin (0.88 and 0.88 against 0.01).
    # Across five seeds it held at four and failed at one, where the factor
    # loaded on behavioural and temporal instead (0.75, 0.75 against -0.28 and
    # 0.11). So it is a property of a seed rather than of the generator, and
    # asserting it would have locked in one draw. The bounds above are what
    # survives all five: shared variance 0.300 to 0.482, largest loading 0.746
    # to 0.919.

    def test_fusion_is_not_summation(self, system, enrolled, analyst, case_ref) -> None:
        """Naive summation counts the shared cause once per stream.

        The whole fusion layer exists to not do that, so on dependent streams the
        two must differ. Equality would mean the fitted model had collapsed to
        independence without anything saying so.
        """
        differences = []
        for first, second in list(_pairs(enrolled))[:40]:
            result = _compare(system, analyst, case_ref, first, second)
            if result.overstatement is not None:
                differences.append(abs(result.overstatement.displacement_log10))
        assert differences, "no comparison produced an overstatement measurement"
        assert max(differences) > 1e-6

    def test_the_fused_interval_has_width(
        self, system, enrolled, analyst, case_ref
    ) -> None:
        """Containment is already a construction invariant of ``ComparisonResult``.

        What is not guaranteed anywhere is that the interval is non-degenerate.
        A fusion provider whose resampling silently collapsed would report a
        point estimate with zero width — a claim of exactness the system has no
        basis for — and every existing check would still pass.
        """
        result = _compare(system, analyst, case_ref, enrolled[0], enrolled[1])
        assert result.uncertainty.upper - result.uncertainty.lower > 0.0


class TestAStreamThatDeclines:
    def test_too_few_calls_is_absence_and_the_rest_still_report(
        self, system, enrolled, analyst, case_ref
    ) -> None:
        """One stream declining must not take the comparison down with it.

        ``TemporalComparator`` refuses below three calls on the stated ground
        that a rhythm cannot be estimated from a handful of records. An
        investigator should still get the other three streams.
        """
        store = system.unit_of_work.store.evidence
        full = store[enrolled[1].value]
        thin = EvidenceBundle(
            incident_id=enrolled[1],
            payloads={
                **full.payloads,
                EvidenceStream.TEMPORAL: TemporalProfile.from_records(
                    [
                        CallRecord(
                            timestamp=record,
                            duration_seconds=90.0,
                        )
                        for record in _two_timestamps()
                    ]
                ),
            },
        )
        result = system.compare.execute(
            ComparisonRequest(
                pair=IncidentPair(enrolled[0], enrolled[1], case_ref),
                prior=PriorOdds.uniform_over_database(64),
                requested_by=analyst,
            ),
            store[enrolled[0].value],
            thin,
        )
        temporal = result.outcomes[EvidenceStream.TEMPORAL]
        assert isinstance(temporal, StreamAbsent)
        assert temporal.reason is AbsenceReason.INSUFFICIENT_DATA
        for stream in (
            EvidenceStream.BEHAVIOURAL,
            EvidenceStream.TRANSACTIONAL,
            EvidenceStream.DEVICE,
        ):
            assert isinstance(result.outcomes[stream], StreamEvidence)

    def test_a_transcript_below_the_floor_is_refused_not_scored(
        self, system, corpus
    ) -> None:
        """``build_profile``'s word floor is the behavioural stream's own
        admission that short text yields sampling noise rather than an idiolect.
        """
        from dataclasses import replace

        from viflap.domain.errors import InsufficientDataError

        short = replace(corpus[0], transcript="good morning madam")
        with pytest.raises(InsufficientDataError):
            payloads_for(short, system.raw.function_words, system.raw.disfluencies)


class TestGovernanceOnRealEvidence:
    def test_the_chain_verifies_after_a_full_session(
        self, system, enrolled, analyst, case_ref
    ) -> None:
        system.search.execute(
            SearchRequest(enrolled[0], case_ref, analyst, max_results=3)
        )
        verification = system.audit.verify()
        assert verification.is_intact
        assert verification.n_entries > len(enrolled)

    def test_everything_emitted_passes_the_output_policy(
        self, system, enrolled, analyst, case_ref
    ) -> None:
        """The policy rejects the vocabulary of identity at the boundary.

        Worth checking on real evidence rather than on a scalar double: these
        caveats interpolate stream names, model identifiers and absence reasons
        that the double never produces.
        """
        result = _compare(system, analyst, case_ref, enrolled[0], enrolled[1])
        for caveat in result.caveats():
            OutputLanguagePolicy.assert_permitted(caveat)
        OutputLanguagePolicy.assert_permitted(result.verbal_summary())

    def test_search_prior_comes_from_the_enrolled_population(
        self, system, enrolled, analyst, case_ref
    ) -> None:
        results = system.search.execute(
            SearchRequest(enrolled[0], case_ref, analyst, max_results=3)
        )
        assert results.prior.population_size == len(enrolled)
        assert results.prior.supplied_by == "system"


class TestTheWiringIsTheRightWayRound:
    """Sign checks, not performance claims. See the module docstring."""

    def test_same_operator_outranks_unrelated_operations_on_the_median(
        self, system, enrolled, analyst, case_ref
    ) -> None:
        """Catches payloads handed to the wrong stream and inverted calibrators.

        Stated on medians over groups rather than on any single pair, because a
        single pair can go either way for reasons that are not defects. It is a
        statement about this generator's parameters and is **not** a measurement
        of anything.
        """
        operator_of = {
            f"ZP-2026-{incident.incident_id}": incident.operator_id
            for incident in system.partitions.evaluation
        }
        operation_of = {
            f"ZP-2026-{incident.incident_id}": incident.operation_id
            for incident in system.partitions.evaluation
        }
        same_operator: list[float] = []
        unrelated: list[float] = []
        for first, second in _pairs(enrolled):
            if operator_of[first.value] == operator_of[second.value]:
                bucket = same_operator
            elif operation_of[first.value] != operation_of[second.value]:
                bucket = unrelated
            else:
                continue
            if len(bucket) >= 60:
                continue
            bucket.append(
                _compare(system, analyst, case_ref, first, second).fused_log_lr.log10
            )

        assert same_operator and unrelated
        assert float(np.median(same_operator)) > float(np.median(unrelated))


class TestTheBoundaryIsStated:
    def test_the_module_refuses_to_let_a_figure_travel_unlabelled(self) -> None:
        """The one thing this corpus must never do is have a number quoted off
        it as a measurement, so the warning is part of the contract."""
        assert "SIMULATION" in WARNING
        assert "No figure in this file is a result" in WARNING


def _two_timestamps():
    from datetime import UTC, datetime

    return [
        datetime(2026, 3, 2, 9, 0, tzinfo=UTC),
        datetime(2026, 3, 2, 11, 0, tzinfo=UTC),
    ]
