"""Train the spoofing countermeasure, and measure how little that is worth.

The validity gate decides whether acoustic evidence reaches fusion at all, and
until now it has had no detector behind it — a policy applied to a score nothing
produced. This script produces one, from real Zambian speech and synthetic
attacks generated from that same speech, so the genuine and spoofed classes
differ in what was done to them and not in who was speaking or what language
they spoke.

Two holdouts, because either alone flatters the result
------------------------------------------------------
**Unseen speakers.** Genuine and spoofed material both derive from the same
recordings, so a speaker appearing on both sides of the split lets the detector
recognise the person rather than the synthesis. Splits are speaker-disjoint.

**Unseen attacks.** This is the one that matters. A countermeasure evaluated on
the attack family it trained on is measuring interpolation, and every published
countermeasure does well at that. The failure mode in service is a synthesis
method released after training, so the number that describes deployment is the
one from leaving an attack family out entirely.

Both are reported. The gap between them is the finding — not a caveat on the
finding — because it estimates what this component loses when the threat
changes, which is the only thing a deployment decision needs from it.

What this cannot tell you
-------------------------
The attacks are vocoder-class, generated by signal processing. A detector that
separates them cleanly has not been shown to detect neural synthesis, and the
cross-attack number here is a *lower bound* on the generalisation gap rather
than an estimate of it: the four families here are more like one another than
any of them is like a diffusion vocoder. The gate's out-of-domain rule exists
for exactly that residue.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import time
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import soundfile as sf
from numpy.typing import NDArray

from scripts.corpus import materialise, scan_corpora
from scripts.corpus_zambian import parse_labelled_name
from viflap.analysis.calibration.metrics import compute_eer
from viflap.analysis.spoof.attacks import ATTACKS, apply_attack
from viflap.analysis.spoof.countermeasure import (
    CountermeasureConfig,
    SpoofingCountermeasure,
    TrainingExample,
)
from viflap.domain.errors import InsufficientDataError

#: Seeds attack generation. Fixed so that a rerun produces the same spoofed
#: material and the same model.
ATTACK_SEED = 20250601


@dataclass(frozen=True, slots=True)
class Recording:
    """One genuine recording, with the speaker the split is made on."""

    signal: NDArray[np.float64]
    sample_rate: int
    speaker_id: str
    recording_id: str


def load_genuine(audio_root: Path, max_recordings: int | None = None) -> list[Recording]:
    """Read genuine speech, keeping only recordings whose speaker is known."""
    recordings: list[Recording] = []
    for path in sorted(audio_root.glob("*.wav"), key=lambda p: p.name):
        parsed = parse_labelled_name(path.name)
        if parsed is None:
            continue
        signal, sample_rate = sf.read(path, dtype="float64")
        if signal.ndim > 1:
            signal = signal.mean(axis=1)
        recordings.append(Recording(signal, int(sample_rate), parsed[0], path.stem))
        if max_recordings is not None and len(recordings) >= max_recordings:
            break

    if not recordings:
        raise InsufficientDataError(f"no usable recordings under {audio_root}")
    return recordings


def load_librispeech(
    roots: Sequence[Path], max_speakers: int | None = None, seconds: float = 12.0
) -> list[Recording]:
    """Read genuine speech from the LibriSpeech tree, one recording per speaker.

    **Speaker diversity is what this training set needs, and it is not the same
    thing the speaker-recognition corpus needs.** A countermeasure separates
    genuine speech from synthesis; it does not model who is speaking, so it has
    no use for several sessions of one person and every use for many different
    people. Taking one recording each from many speakers spends the same number
    of files on far more voices.

    Kept short deliberately: attack generation runs at roughly real time, so
    duration trades directly against how many speakers fit in a run, and voices
    are worth more here than seconds.
    """
    plans = scan_corpora(list(roots), target_seconds=seconds, max_recordings_per_session=1)

    seen: set[str] = set()
    chosen = []
    for plan in plans:
        if plan.speaker_id in seen:
            continue
        seen.add(plan.speaker_id)
        chosen.append(plan)
        if max_speakers is not None and len(chosen) >= max_speakers:
            break

    recordings = [
        Recording(item.signal, item.sample_rate, item.speaker_id, item.recording_id)
        for item in materialise(chosen)
    ]
    if not recordings:
        raise InsufficientDataError(f"no usable recordings under {roots}")
    return recordings


def build_examples(
    recordings: Sequence[Recording], attack_ids: Sequence[str]
) -> list[TrainingExample]:
    """One genuine example per recording, plus one per attack family.

    Every attack derives from the recording beside it, so the two classes are
    matched on speaker, language, channel and content. Whatever separates them
    is the synthesis.
    """
    examples: list[TrainingExample] = []
    for recording in recordings:
        examples.append(
            TrainingExample(
                signal=recording.signal,
                sample_rate=recording.sample_rate,
                is_bona_fide=True,
                attack_id="none",
            )
        )
        for attack_id in attack_ids:
            # A content hash, not the built-in one: string hashing is salted per
            # interpreter, so `hash` would give the same recording a different
            # attack realisation on every run and the model would stop being
            # reproducible without anything appearing to change.
            digest = hashlib.sha256(
                f"{recording.recording_id}:{attack_id}".encode()
            ).digest()
            rng = np.random.default_rng(ATTACK_SEED + int.from_bytes(digest[:4], "big"))
            examples.append(
                TrainingExample(
                    signal=apply_attack(
                        attack_id, recording.signal, recording.sample_rate, rng
                    ),
                    sample_rate=recording.sample_rate,
                    is_bona_fide=False,
                    attack_id=attack_id,
                )
            )
    return examples


def split_speakers(
    recordings: Sequence[Recording], evaluation_fraction: float, seed: int
) -> tuple[list[Recording], list[Recording]]:
    """Partition by speaker, never by recording."""
    speakers = sorted({r.speaker_id for r in recordings})
    rng = np.random.default_rng(seed)
    order = rng.permutation(len(speakers))
    n_evaluation = max(1, int(round(len(speakers) * evaluation_fraction)))
    held_out = {speakers[int(i)] for i in order[:n_evaluation]}

    train = [r for r in recordings if r.speaker_id not in held_out]
    evaluate = [r for r in recordings if r.speaker_id in held_out]
    if not train or not evaluate:
        raise InsufficientDataError(
            "the speaker split left one side empty",
            n_speakers=len(speakers),
            n_held_out=len(held_out),
        )
    return train, evaluate


def score_examples(
    countermeasure: SpoofingCountermeasure, examples: Sequence[TrainingExample]
) -> tuple[NDArray[np.float64], NDArray[np.int64]]:
    """Score examples, returning the scores and their genuine/spoofed labels."""
    scores: list[float] = []
    labels: list[int] = []
    for example in examples:
        try:
            result = countermeasure.score(example.signal, example.sample_rate)
        except InsufficientDataError:
            continue
        scores.append(result.log_likelihood_ratio)
        labels.append(1 if example.is_bona_fide else 0)
    return np.asarray(scores), np.asarray(labels, dtype=np.int64)


def evaluate(
    countermeasure: SpoofingCountermeasure, examples: Sequence[TrainingExample]
) -> dict[str, float]:
    scores, labels = score_examples(countermeasure, examples)
    if labels.size == 0 or labels.min() == labels.max():
        return {"equal_error_rate": float("nan"), "n_scored": float(labels.size)}
    return {
        "equal_error_rate": float(compute_eer(scores, labels)),
        "n_scored": float(labels.size),
        "n_genuine": float(int((labels == 1).sum())),
        "n_spoofed": float(int((labels == 0).sum())),
    }


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--audio", type=Path, default=Path("data/corpus/bembaspeech/bem/audio")
    )
    parser.add_argument("--output", type=Path, default=Path("models/countermeasure.npz"))
    parser.add_argument(
        "--report", type=Path, default=Path("data/reports/countermeasure.json")
    )
    parser.add_argument("--components", type=int, default=32)
    parser.add_argument("--max-recordings", type=int, default=None)
    parser.add_argument("--evaluation-fraction", type=float, default=0.34)
    parser.add_argument("--seed", type=int, default=ATTACK_SEED)
    parser.add_argument(
        "--train-corpus",
        type=Path,
        action="append",
        default=None,
        help=(
            "LibriSpeech root(s) to train on, one recording per speaker. A "
            "countermeasure needs many voices rather than many sessions of a "
            "few, and these corpora carry hundreds of speakers where the "
            "Zambian ones carry tens."
        ),
    )
    parser.add_argument("--max-train-speakers", type=int, default=300)
    parser.add_argument(
        "--holdout-audio",
        type=Path,
        default=None,
        help=(
            "genuine speech held out entirely, in a different language. Makes "
            "the evaluation cross-lingual as well as cross-speaker, which is "
            "the question a Zambian deployment actually asks of a detector "
            "trained on English."
        ),
    )
    arguments = parser.parse_args(argv)

    if arguments.train_corpus:
        print(f"loading training speech from {arguments.train_corpus}", flush=True)
        train_recordings = load_librispeech(
            arguments.train_corpus, arguments.max_train_speakers
        )
        print(f"  {len(train_recordings)} recordings, one per speaker", flush=True)

        holdout = arguments.holdout_audio or arguments.audio
        print(f"holding out {holdout} entirely", flush=True)
        eval_recordings = load_genuine(holdout, arguments.max_recordings)
        recordings = [*train_recordings, *eval_recordings]
        speakers = sorted({r.speaker_id for r in recordings})
        print(
            f"  {len(eval_recordings)} held-out recordings from "
            f"{len({r.speaker_id for r in eval_recordings})} speakers",
            flush=True,
        )
    else:
        print(f"loading genuine speech from {arguments.audio}", flush=True)
        recordings = load_genuine(arguments.audio, arguments.max_recordings)
        speakers = sorted({r.speaker_id for r in recordings})
        print(f"  {len(recordings)} recordings from {len(speakers)} speakers", flush=True)

        train_recordings, eval_recordings = split_speakers(
            recordings, arguments.evaluation_fraction, arguments.seed
        )

    print(
        f"  split: {len({r.speaker_id for r in train_recordings})} train speakers, "
        f"{len({r.speaker_id for r in eval_recordings})} held out",
        flush=True,
    )

    attack_ids = sorted(ATTACKS)
    config = CountermeasureConfig(n_components=arguments.components)

    print(f"generating {len(attack_ids)} attack families", flush=True)
    started = time.monotonic()
    train_examples = build_examples(train_recordings, attack_ids)
    eval_examples = build_examples(eval_recordings, attack_ids)
    print(
        f"  {len(train_examples)} train, {len(eval_examples)} evaluation examples "
        f"in {time.monotonic() - started:.0f}s",
        flush=True,
    )

    # -- Seen attacks: the optimistic number ------------------------------
    print("training on all attack families", flush=True)
    started = time.monotonic()
    full = SpoofingCountermeasure.train(train_examples, config)
    print(f"  trained in {(time.monotonic() - started) / 60:.1f} min", flush=True)

    seen = evaluate(full, eval_examples)
    print(f"  unseen speakers, seen attacks: EER {seen['equal_error_rate']:.2%}")

    # -- Unseen attacks: the number that describes deployment -------------
    cross: dict[str, dict[str, float]] = {}
    for held_out in attack_ids:
        remaining = [a for a in attack_ids if a != held_out]
        subset = [e for e in train_examples if e.is_bona_fide or e.attack_id in remaining]
        held_examples = [
            e for e in eval_examples if e.is_bona_fide or e.attack_id == held_out
        ]
        print(f"holding out {held_out}", flush=True)
        model = SpoofingCountermeasure.train(subset, config)
        cross[held_out] = evaluate(model, held_examples)
        print(f"  EER on unseen {held_out}: {cross[held_out]['equal_error_rate']:.2%}")

    rates = [
        v["equal_error_rate"] for v in cross.values() if np.isfinite(v["equal_error_rate"])
    ]
    report = {
        "detector_id": full.detector_id,
        "n_recordings": len(recordings),
        "n_speakers": len(speakers),
        "train_speakers": sorted({r.speaker_id for r in train_recordings}),
        "evaluation_speakers": sorted({r.speaker_id for r in eval_recordings}),
        "attacks": {aid: ATTACKS[aid].description for aid in attack_ids},
        "training_summary": full.training_summary,
        "seen_attacks": seen,
        "unseen_attacks": cross,
        "mean_unseen_attack_eer": float(np.mean(rates)) if rates else float("nan"),
        "generalisation_gap": (
            float(np.mean(rates) - seen["equal_error_rate"]) if rates else float("nan")
        ),
        "caveat": (
            "Attacks are vocoder-class, generated by signal processing. The "
            "cross-attack figure is a lower bound on the generalisation gap: "
            "these four families resemble one another more than any resembles "
            "neural synthesis."
        ),
    }

    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    full.save(arguments.output)
    arguments.report.parent.mkdir(parents=True, exist_ok=True)
    arguments.report.write_text(json.dumps(report, indent=2), encoding="utf-8")

    print(f"\nseen attacks     EER {seen['equal_error_rate']:.2%}")
    print(f"unseen attacks   EER {report['mean_unseen_attack_eer']:.2%} (mean)")
    print(f"generalisation gap {report['generalisation_gap']:+.2%}")
    print(f"wrote {arguments.output} and {arguments.report}", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
