"""Voice activity detection.

Getting this wrong is a quiet and expensive failure. Every statistic downstream
— filterbank statistics for the universal background model, the i-vector, the
speaking-rate estimate, the pause distribution — is computed over the frames
this module admits. Admitting silence biases the models toward the *channel*,
because silence in a coded telephone call is not silence: it is comfort noise
generated by the network, and it characterises the network rather than the
speaker. A system trained on it learns to recognise operators, not people.

The detector combines three cues, because none is sufficient alone under the
conditions this system operates in:

**Energy relative to an adaptive floor.** Absolute thresholds do not survive the
level variation between handsets and networks. The floor is estimated as a low
percentile of the frame energy distribution within the recording, so the
decision is scale-invariant.

**Spectral flatness.** Comfort noise and stationary background noise are
spectrally flat; voiced speech is not, having a strong harmonic structure.
Flatness separates a loud noisy passage from a loud speech passage, which energy
alone cannot.

**Temporal continuity.** Speech occurs in runs. A hangover extends a detected
region past its trailing edge so that low-energy fricatives and final devoicing
are not clipped, and a minimum-duration rule removes isolated frames that survive
the first two tests by chance.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray

from viflap.analysis.dsp.framing import FrameConfig, FrameGeometry, frame_signal
from viflap.analysis.dsp.spectral import power_spectrum
from viflap.domain.errors import InsufficientDataError, InvalidEvidenceError

__all__ = ["VadConfig", "VadResult", "detect_voice_activity", "spectral_flatness"]


def spectral_flatness(
    spectra: NDArray[np.float64], floor: float = 1e-12
) -> NDArray[np.float64]:
    """Wiener entropy: the ratio of geometric to arithmetic mean power per frame.

    Ranges over ``(0, 1]``. A value near one means the spectrum is flat — white
    noise, or the comfort noise a network inserts during silence. Values well
    below one indicate concentrated spectral structure, which for a speech
    signal means harmonics and formants.

    Computed via the log-mean rather than an explicit product: the product of a
    hundred-odd bin powers underflows to zero immediately.
    """
    safe = np.maximum(spectra, floor)
    log_geometric_mean = np.mean(np.log(safe), axis=-1)
    arithmetic_mean = np.mean(safe, axis=-1)
    return np.exp(log_geometric_mean) / np.maximum(arithmetic_mean, floor)


@dataclass(frozen=True, slots=True)
class VadConfig:
    """Voice activity detection parameters."""

    energy_percentile: float = 10.0
    """Percentile of frame log-energy taken as the noise floor. Robust to the
    long silences typical of a call recording, where a simple minimum would sit
    on a single dropout frame."""

    energy_threshold_db: float = 8.0
    """How far above the estimated floor a frame must sit to count as speech.
    Eight decibels is conservative for narrowband telephony: lower values admit
    breath and line noise, higher values clip weak fricatives, and fricatives
    are already scarce after the codec has removed everything above 3.4 kHz."""

    max_flatness: float = 0.55
    """Frames flatter than this are rejected regardless of energy. Rejects loud
    stationary noise, which energy alone accepts."""

    hangover_frames: int = 8
    """Frames appended after a speech region ends, roughly 80 ms. Retains
    utterance-final fricatives and devoiced segments, which fall below the
    energy threshold while still carrying speaker information."""

    min_speech_frames: int = 10
    """Regions shorter than this are discarded, roughly 100 ms — below the
    duration of a syllable. Removes isolated frames that pass the tests by
    chance, principally transients from packet loss concealment."""

    min_speech_fraction: float = 0.05
    """If less than this fraction of frames is retained, the detector reports
    failure rather than returning a handful of frames. Downstream models would
    otherwise produce a confident-looking estimate from almost no data."""

    def __post_init__(self) -> None:
        if not 0.0 < self.energy_percentile < 100.0:
            raise InvalidEvidenceError(
                "energy percentile must lie in (0, 100)",
                energy_percentile=self.energy_percentile,
            )
        if not 0.0 < self.max_flatness <= 1.0:
            raise InvalidEvidenceError(
                "spectral flatness threshold must lie in (0, 1]",
                max_flatness=self.max_flatness,
            )
        if self.hangover_frames < 0 or self.min_speech_frames < 1:
            raise InvalidEvidenceError("frame counts must be non-negative")


@dataclass(frozen=True, slots=True)
class VadResult:
    """Which frames carry speech, and the diagnostics behind the decision."""

    is_speech: NDArray[np.bool_]
    geometry: FrameGeometry
    log_energy: NDArray[np.float64]
    flatness: NDArray[np.float64]
    noise_floor_db: float

    @property
    def n_speech_frames(self) -> int:
        return int(np.count_nonzero(self.is_speech))

    @property
    def speech_fraction(self) -> float:
        if self.geometry.n_frames == 0:
            return 0.0
        return self.n_speech_frames / self.geometry.n_frames

    @property
    def speech_duration_seconds(self) -> float:
        """Net speech duration.

        This — not the file length — is the quantity that governs how much
        evidence a recording can carry, and it is reported with every acoustic
        result. A ninety-second call with eight seconds of the offender speaking
        supports far less than its duration suggests.
        """
        return self.n_speech_frames * self.geometry.frame_shift / self.geometry.sample_rate

    def speech_segments(self) -> list[tuple[float, float]]:
        """Contiguous speech regions as ``(start, end)`` times in seconds."""
        segments: list[tuple[float, float]] = []
        shift = self.geometry.frame_shift / self.geometry.sample_rate
        length = self.geometry.frame_length / self.geometry.sample_rate
        start: int | None = None
        for index, active in enumerate(self.is_speech):
            if active and start is None:
                start = index
            elif not active and start is not None:
                segments.append((start * shift, (index - 1) * shift + length))
                start = None
        if start is not None:
            segments.append((start * shift, (len(self.is_speech) - 1) * shift + length))
        return segments

    def pause_durations(self) -> NDArray[np.float64]:
        """Durations of inter-speech pauses, in seconds.

        Pause structure is a prosodic speaker characteristic and is consumed by
        the behavioural stream. It is derived here rather than re-detected there
        so that both streams agree on where speech is.
        """
        segments = self.speech_segments()
        if len(segments) < 2:
            return np.zeros(0, dtype=np.float64)
        return np.array(
            [segments[i + 1][0] - segments[i][1] for i in range(len(segments) - 1)],
            dtype=np.float64,
        )


def detect_voice_activity(
    signal: NDArray[np.float64],
    frame_config: FrameConfig,
    vad_config: VadConfig | None = None,
    *,
    rng: np.random.Generator | None = None,
) -> VadResult:
    """Detect speech frames.

    Raises
    ------
    InsufficientDataError
        If too little speech is found. Refusing is the correct behaviour: a
        model handed twenty frames returns a number, and that number carries an
        implied precision the data does not support. The refusal propagates as
        an absent stream with a stated reason, which an investigator can read,
        rather than as a weak likelihood ratio, which they cannot distinguish
        from a genuine finding.
    """
    config = vad_config or VadConfig()
    frames, geometry = frame_signal(signal, frame_config, rng=rng)

    energy = np.sum(frames**2, axis=1)
    log_energy_db = 10.0 * np.log10(np.maximum(energy, 1e-12))

    spectra = power_spectrum(frames, frame_config.n_fft)
    flatness = spectral_flatness(spectra)

    noise_floor_db = float(np.percentile(log_energy_db, config.energy_percentile))
    above_floor = log_energy_db > (noise_floor_db + config.energy_threshold_db)
    structured = flatness < config.max_flatness
    candidate = above_floor & structured

    decision = _apply_hangover(candidate, config.hangover_frames)
    decision = _remove_short_regions(decision, config.min_speech_frames)

    result = VadResult(
        is_speech=decision,
        geometry=geometry,
        log_energy=log_energy_db,
        flatness=flatness,
        noise_floor_db=noise_floor_db,
    )

    if result.speech_fraction < config.min_speech_fraction:
        raise InsufficientDataError(
            "too little speech detected for the recording to support analysis",
            speech_fraction=round(result.speech_fraction, 4),
            required_fraction=config.min_speech_fraction,
            speech_seconds=round(result.speech_duration_seconds, 2),
            total_seconds=round(geometry.duration_seconds, 2),
        )
    return result


def _apply_hangover(decision: NDArray[np.bool_], hangover: int) -> NDArray[np.bool_]:
    """Extend each speech region forward by ``hangover`` frames.

    Implemented as a maximum filter over a trailing window: a frame is retained
    if any of the preceding ``hangover`` frames was speech. The equivalent loop
    is O(n * hangover) and this is O(n).
    """
    if hangover <= 0:
        return decision
    extended = decision.copy()
    padded = np.concatenate([np.zeros(hangover, dtype=bool), decision])
    for offset in range(1, hangover + 1):
        extended |= padded[hangover - offset : hangover - offset + decision.size]
    return extended


def _remove_short_regions(decision: NDArray[np.bool_], minimum: int) -> NDArray[np.bool_]:
    """Zero out speech regions shorter than ``minimum`` frames."""
    if minimum <= 1 or decision.size == 0:
        return decision
    cleaned = decision.copy()
    # Boundaries where the decision changes; run lengths follow from their gaps.
    padded = np.concatenate([[False], decision, [False]])
    changes = np.flatnonzero(padded[1:] != padded[:-1])
    for start, end in zip(changes[::2], changes[1::2], strict=False):
        if end - start < minimum:
            cleaned[start:end] = False
    return cleaned
